### ISSUE TITLE
tcsetattr: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by zer0ty** [b23r0/rsocx#13] opened 2022-08-23 09:18 UTC
this is my way to use rsocx:
1. reverse bash 
2. wget download rsocx
3. run

question:
just run a few minutes ,then  this error occurred
![捕获](https://user-images.githubusercontent.com/100894276/186121398-f90ccfa9-5209-4d38-9632-0a36c9c48296.PNG)

**Comment by b23r0** [comment] 2022-08-23 14:03
1. according to the log, you need to use a socks5 client to use rsocx. rsocx does not support socks4 version.
2. tcsetattr() error may not from rsocx, you need to further check the reverse shell tool for problems.

**Comment by b23r0** [comment] 2022-08-23 14:12
maybe you were caught by the administrator and terminated the program. or discovered by HIDS software.

I can't reproduce this problem.

**Comment by zer0ty** [comment] 2022-08-24 01:19
> 1. according to the log, you need to use a socks5 client to use rsocx. rsocx does not support socks4 version.
> 2. tcsetattr() error may not from rsocx, you need to further check the reverse shell tool for problems.

1. Both the server and the client use this rsocx， so i also curious about error with socks4
2. i run rscox with low privilege user, like apache, i don't know this will have a impact or not
3. About Administrator, i think it's not, beacuse rsocx will close at the same time each times
4. HIDS will not also， i have checked all process

so i just doubt Whether or not the IO or permissions, and other problems caused this error

**Comment by b23r0** [comment] 2022-08-25 08:32
By socks5 client I mean local software like `proxifier` that provides local proxy services. rsocx does not provide socks5 client functionality.

Running rsocx is not directly related to permissions, and low-privilege environments can still be used.

If the process terminates for unknown reasons. I think it is also necessary to check whether the running environment has enough memory, or whether there is a requirement for the number of process fds, and what other constraints the operating system has.

Would like to provide more information about the running environment, such as OS version, memory, etc.

**Comment by zer0ty** [comment] 2022-08-30 09:11
> 

sorry, i have lost that enviroment. If i meet next time, I will provide more information

**Comment by b23r0** [comment] 2022-08-30 15:08
Thank you for raising an issue. If you encounter new problems in the future, you can still raise a new issue. I will close this issue as there is no new progress.

**Closed as completed by b23r0** 2022-08-30 15:08 UTC
